name: Sync api.h and vmlinux.h from latest kernel
on:
  workflow_dispatch:
    inputs:
      linux-release:
        description: 'Linux kernel release to run against'
        required: false
        type: string
  schedule:
    - cron: '0 2 * * 1' # each monday at 2:00

jobs:
  load-latest-kernel-release:
    runs-on: 'ubuntu-24.04'
    outputs:
      release: ${{ steps.kernel.outputs.release }}
    steps:
      # inputs.linux-release takes precedence.
      # If empty, we fetch latest tag on torvalds/linux repo.
      # Skip RCs.
      - name: Load latest linux tag
        id: kernel
        run: |
          ktag=${{ inputs.linux-release }}
          if [[ -z "${ktag}" ]]; then
            ktag=$(curl  "https://api.github.com/repos/torvalds/linux/tags" | jq -r '.[0].name')
            echo "using latest linux release: ${ktag}"
          else
            echo "enforcing requested linux release: ${ktag}"
          fi
          if [[ "${ktag}" == *-rc* ]]; then
            echo "Skipping job execution for RC: ${ktag}."
          else
            echo "release=${ktag}" >> "$GITHUB_OUTPUT"
          fi

  sync-api-vmlinux:
    needs: load-latest-kernel-release
    if: needs.load-latest-kernel-release.outputs.release != ''
    runs-on: ${{ (matrix.arch == 'arm64' && 'ubuntu-24.04-arm') || 'ubuntu-24.04' }}
    strategy:
      matrix:
        arch: [ x86, arm64 ]
        include:
          - arch: x86
            deb_arch: amd64
          - arch: arm64
            deb_arch: arm64
    steps:
      - name: Install bpftool
        uses: mtardy/setup-bpftool@9bc044304197616a6321d452e04cc059e006d8e2 # v1.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download requested kernel image from ubuntu mainline ppa
        run: |
          image=$(wget -qO- https://kernel.ubuntu.com/mainline/${{ needs.load-latest-kernel-release.outputs.release }}/${{ matrix.deb_arch }}/ | grep "linux-image-*" | awk '{split($0,file,"\""); print file[8]}' | head -n1)
          wget -O image.deb https://kernel.ubuntu.com/mainline/${{ needs.load-latest-kernel-release.outputs.release }}/${{ matrix.deb_arch }}/$image
          mkdir image
          dpkg-deb -R image.deb image/

      - name: Download extract-kernel script from upstream linux repo
        run: |
          wget -O extract-vmlinux https://raw.githubusercontent.com/torvalds/linux/refs/heads/master/scripts/extract-vmlinux
          chmod +x extract-vmlinux

      - name: Extract vmlinuz
        run: |
          ./extract-vmlinux image/boot/vmlinuz-* > decomp-vmlinuz

      - name: Generate updated vmlinux_generated
        run: |
          mkdir out
          bpftool btf dump file decomp-vmlinuz format c > out/vmlinux_generated_${{ matrix.arch }}.h

      - name: Sync bpf_helper_defs.h from upstream libbpf repo (x86 only)
        if: matrix.arch == 'x86'
        run: |
          wget -O out/bpf_helper_defs.h https://raw.githubusercontent.com/libbpf/libbpf/refs/heads/master/src/bpf_helper_defs.h
          sed -i 's/const bpf_/const /g' bpf_helper_defs.h 

      - name: upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: sync_${{ matrix.arch }}
          path: 'out/*.h'
          if-no-files-found: error

  create-pr:
    needs: [load-latest-kernel-release, sync-api-vmlinux]
    if: needs.load-latest-kernel-release.outputs.release != ''
    permissions:
      contents: write
      pull-requests: write
    runs-on: 'ubuntu-24.04'
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Download x86 artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: sync_x86
          path: bpf/include/

      - name: Download arm64 artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: sync_arm64
          path: bpf/include/

      # In case of no diff, this won't create any PR.
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          signoff: true
          base: main
          branch: sync/bpf_headers
          title: 'sync(bpf): update bpf api and vmlinux_generated headers'
          body: |
            This automatic PR syncs bpf api and vmlinux_generated headers from latest kernel: ${{ needs.load-latest-kernel-release.outputs.release }}. Do not edit this PR.
          commit-message: 'sync(bpf): update bpf api and vmlinux_generated headers.'
          token: ${{ secrets.GITHUB_TOKEN }}