name: Sync api.h and vmlinux.h from latest kernel
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 1 * *' # first day of each month

jobs:
  sync-api-vmlinux:
    runs-on: ${{ (matrix.arch == 'arm64' && 'ubuntu-24.04-arm') || 'ubuntu-24.04' }}
    strategy:
      matrix:
        arch: [ x86, arm64 ]
        include:
          - arch: x86
            tumbleweed_repo: 'https://download.opensuse.org/tumbleweed/repo/oss/x86_64/'
          - arch: arm64
            tumbleweed_repo: 'https://download.opensuse.org/ports/aarch64/tumbleweed/repo/oss/aarch64/'
    steps:
      - name: Install bpftool
        uses: mtardy/setup-bpftool@9bc044304197616a6321d452e04cc059e006d8e2 # v1.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download most recent kernel package from opensuse tumbleweed
        run: |
          image=$(wget -qO- ${{ matrix.tumbleweed_repo }} | grep "kernel-default-base-*" | head -n1 | awk '{split($0,file,"\""); print file[4]}')
          wget -O image.rpm ${{ matrix.tumbleweed_repo }}$image
          mkdir image && cd image
          rpm2cpio ../image.rpm | cpio -idmv
          prefix="./kernel-default-base-"
          suffix=".rpm"
          version=${image#"$prefix"}
          version=${version%"$suffix"}
          echo "KERNEL_VERSION=$version" >> $GITHUB_ENV

      - name: Download extract-kernel script from upstream linux repo
        run: |
          wget -O extract-vmlinux https://raw.githubusercontent.com/torvalds/linux/refs/heads/master/scripts/extract-vmlinux
          chmod +x extract-vmlinux

      - name: Extract vmlinuz
        run: |
          ./extract-vmlinux image/usr/lib/modules/*/vmlinux.xz > decomp-vmlinuz

      - name: Generate updated vmlinux_generated
        run: |
          mkdir out
          bpftool btf dump file decomp-vmlinuz format c > out/vmlinux_generated_${{ matrix.arch }}.h
          sed -i '1i// Autogenerated from opensuse tumbleweed ${{ env.KERNEL_VERSION }} kernel' out/vmlinux_generated_${{ matrix.arch }}.h

      - name: Sync bpf_helper_defs.h from upstream libbpf repo (x86 only)
        if: matrix.arch == 'x86'
        run: |
          wget -O out/bpf_helper_defs.h https://raw.githubusercontent.com/libbpf/libbpf/refs/heads/master/src/bpf_helper_defs.h
          sed -i 's/const bpf_/const /g' out/bpf_helper_defs.h
          sed -i '1i// Autogenerated from libbpf sources' out/bpf_helper_defs.h

      - name: upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: sync_${{ matrix.arch }}
          path: 'out/*.h'
          if-no-files-found: error

  create-pr:
    needs: [sync-api-vmlinux]
    permissions:
      contents: write
      pull-requests: write
    runs-on: 'ubuntu-24.04'
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Download x86 artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: sync_x86
          path: bpf/include/

      - name: Download arm64 artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: sync_arm64
          path: bpf/include/

      # In case of no diff, this won't create any PR.
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          signoff: true
          base: main
          branch: sync/bpf_headers
          title: 'sync(bpf): update bpf api and vmlinux_generated headers'
          body: |
            This automatic PR syncs bpf api and vmlinux_generated headers from latest upstream. Do not edit this PR.
          commit-message: 'sync(bpf): update bpf api and vmlinux_generated headers.'
          token: ${{ secrets.GITHUB_TOKEN }}